# Generated by Django 5.1.2 on 2024-11-05 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0008_customuser_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_reason', models.CharField(max_length=100)),
                ('leave_start_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('leave_status', models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approve'), ('rejection', 'Rejection')], default='pending', max_length=10)),
                ('leave_created', models.DateTimeField(auto_now_add=True)),
                ('leave_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyWorkReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=100)),
                ('work_description', models.TextField()),
                ('work_status', models.CharField(max_length=100)),
                ('work_created', models.DateTimeField(auto_now_add=True)),
                ('work_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
