# Generated by Django 5.1.2 on 2024-11-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0009_applicationleave_dailyworkreports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyworkreports',
            name='work_status',
        ),
    ]
